In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


pd.set_option('display.max_columns', None)
prefix = "../data/processed/"

In [2]:
#RP data sets have regular games and playoff games 
df_base_RP = pd.read_csv(prefix + "TeamStatisticsFrom2010RP.csv")
df_roll_RP = pd.read_csv(prefix + "TeamStatisticsFrom2010RPRoll10.csv")
df_match_RP = pd.read_csv(prefix + "TeamStatisticsFrom2010RPMatchups.csv")

#Reg data sets have just regular games 
df_base_Rg = pd.read_csv(prefix + "TeamStatisticsFrom2010Reg.csv")
df_roll_Rg = pd.read_csv(prefix + "TeamStatisticsFrom2010RegRoll10.csv")
df_match_Rg = pd.read_csv(prefix + "TeamStatisticsFrom2010RegMatchups.csv")

In [3]:
df_base_RP.columns

Index(['gameId', 'gameDate', 'season', 'teamId', 'teamName', 'opponentTeamId',
       'opponentTeamName', 'home', 'win', 'teamScore', 'opponentScore',
       'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'reboundsOffensive', 'reboundsDefensive',
       'assists', 'turnovers', 'steals', 'blocks', 'plusMinusPoints',
       'rest_days', 'b2b'],
      dtype='str')

In [4]:
df_roll_RP.columns

Index(['gameId', 'gameDate', 'season', 'teamId', 'teamName', 'opponentTeamId',
       'opponentTeamName', 'home', 'win', 'teamScore', 'opponentScore',
       'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'reboundsOffensive', 'reboundsDefensive',
       'assists', 'turnovers', 'steals', 'blocks', 'plusMinusPoints',
       'rest_days', 'b2b', 'teamScore_roll10', 'fieldGoalsPercentage_roll10',
       'threePointersPercentage_roll10', 'freeThrowsPercentage_roll10',
       'reboundsOffensive_roll10', 'reboundsDefensive_roll10',
       'assists_roll10', 'turnovers_roll10', 'steals_roll10', 'blocks_roll10',
       'plusMinusPoints_roll10', 'win_roll10'],
      dtype='str')

In [5]:
df_match_RP.columns

Index(['gameId', 'gameDate', 'season', 'home_teamId', 'home_teamName',
       'home_rest_days', 'home_b2b', 'win', 'home_teamScore_roll10',
       'home_fieldGoalsPercentage_roll10',
       'home_threePointersPercentage_roll10',
       'home_freeThrowsPercentage_roll10', 'home_reboundsOffensive_roll10',
       'home_reboundsDefensive_roll10', 'home_assists_roll10',
       'home_turnovers_roll10', 'home_steals_roll10', 'home_blocks_roll10',
       'home_plusMinusPoints_roll10', 'home_win_roll10', 'away_teamId',
       'away_teamName', 'away_rest_days', 'away_b2b', 'away_teamScore_roll10',
       'away_fieldGoalsPercentage_roll10',
       'away_threePointersPercentage_roll10',
       'away_freeThrowsPercentage_roll10', 'away_reboundsOffensive_roll10',
       'away_reboundsDefensive_roll10', 'away_assists_roll10',
       'away_turnovers_roll10', 'away_steals_roll10', 'away_blocks_roll10',
       'away_plusMinusPoints_roll10', 'away_win_roll10',
       'teamScore_roll10_diff', 'fieldGoalsP

In [ ]:
#Rollig data set test and train
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(df_roll['home'], df_roll['win'], random_state=17, test_size=0.2)


In [16]:
df2 = df_roll[ll].dropna(how='all').dropna(how='all', axis=1)
if (len(df2) < 50): print(df2)

In [17]:
df2

,teamScore,opponentScore,fieldGoalsPercentage,threePointersPercentage,freeThrowsPercentage,reboundsOffensive,reboundsDefensive,assists,turnovers,steals,blocks,plusMinusPoints,teamScore_roll10,fieldGoalsPercentage_roll10,threePointersPercentage_roll10,freeThrowsPercentage_roll10,reboundsOffensive_roll10,reboundsDefensive_roll10,assists_roll10,turnovers_roll10,steals_roll10,blocks_roll10,plusMinusPoints_roll10,win_roll10
0,111,115,0.519,0.222,0.614,9,30,26,26,9,1,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,85,94,0.441,0.538,0.692,9,32,22,21,6,2,-9.0,111.0,0.51900,0.2220,0.614000,9.000000,30.000000,26.000000,26.00,9.000000,1.0,-4.000000,0.00
2,92,107,0.513,0.500,0.400,7,24,19,16,5,3,-15.0,98.0,0.48000,0.3800,0.653000,9.000000,31.000000,24.000000,23.50,7.500000,1.5,-6.500000,0.00
3,84,74,0.406,0.278,0.676,5,31,18,16,9,6,10.0,96.0,0.49100,0.4200,0.568667,8.333333,28.666667,22.333333,21.00,6.666667,2.0,-9.333333,0.00
4,73,102,0.308,0.188,0.759,9,24,15,6,7,2,-29.0,93.0,0.46975,0.3845,0.595500,7.500000,29.250000,21.250000,19.75,7.250000,3.0,-4.500000,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43521,102,113,0.432,0.327,0.769,14,26,24,12,5,3,-11.0,121.0,0.48550,0.3935,0.819700,13.000000,33.800000,26.700000,13.40,6.400000,3.4,16.400000,0.80
43522,100,118,0.386,0.277,0.826,14,27,16,15,10,8,-18.0,118.2,0.47620,0.3784,0.807700,13.400000,33.300000,26.300000,12.40,6.000000,3.5,13.400000,0.70
43523,110,96,0.459,0.365,0.765,12,34,27,17,7,7,14.0,115.8,0.46190,0.3642,0.823600,13.500000,32.400000,25.400000,12.20,6.300000,3.9,9.300000,0.60
43524,127,126,0.442,0.321,1.000,17,37,26,6,4,7,1.0,113.4,0.45670,0.3534,0.825100,13.500000,31.300000,24.900000,12.60,6.300000,4.1,6.300000,0.60


In [10]:
#Naive Bayes using roll10 variables that we would have access to before a prediction 
#RP data set
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import roc_auc_score, precision_score

ll_roll_rp = ['home', 'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'reboundsOffensive', 'reboundsDefensive',
       'assists', 'turnovers', 'steals', 'blocks', 'plusMinusPoints',
       'rest_days', 'b2b', 'teamScore_roll10', 'fieldGoalsPercentage_roll10',
       'threePointersPercentage_roll10', 'freeThrowsPercentage_roll10',
       'reboundsOffensive_roll10', 'reboundsDefensive_roll10',
       'assists_roll10', 'turnovers_roll10', 'steals_roll10', 'blocks_roll10',
       'plusMinusPoints_roll10', 'win_roll10','win']

df_rrp = df_roll_RP[ll_roll_rp].dropna()
y_rrp  = df_rrp['win']
r_dic = {}

#Loop that iterates over each column in the above list, fits, and calculates the accuracy
#Only models/variables that yield results better than chance are reported
for col in ll_roll_rp:
    if col == 'win':continue
    kf       = KFold(n_splits=5)
    stat_ary = np.zeros((3, 5))
    x_tr, x_te, y_tr, y_te = train_test_split(df_rrp[col], y_rrp, random_state=17, test_size=0.2)
    
    for i, (train_ix, test_ix) in enumerate(kf.split(x_tr)):
       xr = x_tr.iloc[train_ix].values.reshape(-1,1)
       yr = y_tr.iloc[train_ix]
       xh = x_tr.iloc[test_ix].values.reshape(-1,1)
       yh = y_tr.iloc[test_ix]
       nb = GaussianNB()
       nb.fit(xr, yr)

       y_pred = nb.predict(xh)
       acc    = 1.0*sum(y_pred==yh) / len(y_pred)
       prob   = nb.predict_proba(xh)
       roc    = roc_auc_score(yh, prob[:,1])
       prec   = precision_score(yh, y_pred)

       stat_ary[0][i] = acc
       stat_ary[1][i] = roc
       stat_ary[2][i] = prec

    if (stat_ary[0].mean() > 0.5 and stat_ary[1].mean() > 0.5 and stat_ary[2].mean() > 0.5):
       rstr = '%s Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = %.3f(%.3f),%.3f(%.3f), %.3f(%.3f)'%(
          col, stat_ary[0].mean(),stat_ary[0].std(), stat_ary[1].mean(),stat_ary[1].std(),stat_ary[2].mean(),stat_ary[2].std())
       acc_m = stat_ary[0].mean()
       r_dic[rstr] = acc_m

#Sorts the results by descending mean accuracty and prints the results
r_sorted = {k : v for k, v in sorted(r_dic.items(), key = lambda item: item[1], reverse=True)}

print('Roll10 Regular + Playoffs Results')
for key, value in r_sorted.items():
   print(key)


Roll10 Regular + Playoffs Results
plusMinusPoints Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 1.000(0.000),1.000(0.000), 1.000(0.000)
fieldGoalsPercentage Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.687(0.004),0.760(0.004), 0.693(0.007)
reboundsDefensive Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.648(0.005),0.703(0.007), 0.668(0.007)
threePointersPercentage Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.642(0.005),0.693(0.005), 0.650(0.008)
assists Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.622(0.006),0.672(0.006), 0.646(0.004)
plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.585(0.007),0.619(0.006), 0.578(0.006)
win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.578(0.004),0.607(0.006), 0.566(0.003)
home Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.577(0.008),0.577(0.008), 0.579(0.007)
blocks Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.565(0.005),0.594(0.004), 0.592(0.006)
steals Mean Acc(STD), Mean ROC(STD), Mean Prec(STD

In [11]:
#Naive Bayes using roll10 variables that we would have access to before a prediction 
#Reg data set
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import roc_auc_score, precision_score

ll_roll_rg = ['home', 'fieldGoalsPercentage', 'threePointersPercentage',
       'freeThrowsPercentage', 'reboundsOffensive', 'reboundsDefensive',
       'assists', 'turnovers', 'steals', 'blocks', 'plusMinusPoints',
       'rest_days', 'b2b', 'teamScore_roll10', 'fieldGoalsPercentage_roll10',
       'threePointersPercentage_roll10', 'freeThrowsPercentage_roll10',
       'reboundsOffensive_roll10', 'reboundsDefensive_roll10',
       'assists_roll10', 'turnovers_roll10', 'steals_roll10', 'blocks_roll10',
       'plusMinusPoints_roll10', 'win_roll10','win']

df_rrg = df_roll_Rg[ll_roll_rg].dropna()
y_rrg  = df_rrg['win']
r_dic = {}

#Loop that iterates over each column in the above list, fits, and calculates the accuracy
#Only models/variables that yield results better than chance are reported
for col in ll_roll_rg:
    if col == 'win':continue
    kf       = KFold(n_splits=5)
    stat_ary = np.zeros((3, 5))
    x_tr, x_te, y_tr, y_te = train_test_split(df_rrg[col], y_rrg, random_state=17, test_size=0.2)
    
    for i, (train_ix, test_ix) in enumerate(kf.split(x_tr)):
       xr = x_tr.iloc[train_ix].values.reshape(-1,1)
       yr = y_tr.iloc[train_ix]
       xh = x_tr.iloc[test_ix].values.reshape(-1,1)
       yh = y_tr.iloc[test_ix]
       nb = GaussianNB()
       nb.fit(xr, yr)

       y_pred = nb.predict(xh)
       acc    = 1.0*sum(y_pred==yh) / len(y_pred)
       prob   = nb.predict_proba(xh)
       roc    = roc_auc_score(yh, prob[:,1])
       prec   = precision_score(yh, y_pred)

       stat_ary[0][i] = acc
       stat_ary[1][i] = roc
       stat_ary[2][i] = prec

    if (stat_ary[0].mean() > 0.5 and stat_ary[1].mean() > 0.5 and stat_ary[2].mean() > 0.5):
       rstr = '%s Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = %.3f(%.3f),%.3f(%.3f), %.3f(%.3f)'%(
          col, stat_ary[0].mean(),stat_ary[0].std(), stat_ary[1].mean(),stat_ary[1].std(),stat_ary[2].mean(),stat_ary[2].std())
       acc_m = stat_ary[0].mean()
       r_dic[rstr] = acc_m

#Sorts the results by descending mean accuracty and prints the results
r_sorted = {k : v for k, v in sorted(r_dic.items(), key = lambda item: item[1], reverse=True)}

print('Roll10 Regular Results')
for key, value in r_sorted.items():
   print(key)


Roll10 Regular Results
plusMinusPoints Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 1.000(0.000),1.000(0.000), 1.000(0.000)
fieldGoalsPercentage Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.689(0.002),0.760(0.002), 0.696(0.005)
reboundsDefensive Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.649(0.005),0.704(0.004), 0.667(0.005)
threePointersPercentage Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.640(0.005),0.689(0.006), 0.648(0.005)
assists Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.623(0.006),0.673(0.006), 0.644(0.006)
plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.589(0.005),0.622(0.009), 0.582(0.006)
win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.584(0.005),0.613(0.008), 0.572(0.005)
home Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.574(0.008),0.574(0.009), 0.576(0.009)
blocks Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.564(0.004),0.594(0.006), 0.591(0.007)
steals Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.552(0

In [12]:
#Naive Bayes using match variables that we would have access to before a prediction 
#RP data set
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import roc_auc_score, precision_score

ll_match_rp = ['home_rest_days', 'home_b2b', 'win', 'home_teamScore_roll10',
       'home_fieldGoalsPercentage_roll10',
       'home_threePointersPercentage_roll10',
       'home_freeThrowsPercentage_roll10', 'home_reboundsOffensive_roll10',
       'home_reboundsDefensive_roll10', 'home_assists_roll10',
       'home_turnovers_roll10', 'home_steals_roll10', 'home_blocks_roll10',
       'home_plusMinusPoints_roll10', 'home_win_roll10', 'away_rest_days', 
       'away_b2b', 'away_teamScore_roll10', 'away_fieldGoalsPercentage_roll10',
       'away_threePointersPercentage_roll10',
       'away_freeThrowsPercentage_roll10', 'away_reboundsOffensive_roll10',
       'away_reboundsDefensive_roll10', 'away_assists_roll10',
       'away_turnovers_roll10', 'away_steals_roll10', 'away_blocks_roll10',
       'away_plusMinusPoints_roll10', 'away_win_roll10',
       'teamScore_roll10_diff', 'fieldGoalsPercentage_roll10_diff',
       'threePointersPercentage_roll10_diff',
       'freeThrowsPercentage_roll10_diff', 'reboundsOffensive_roll10_diff',
       'reboundsDefensive_roll10_diff', 'assists_roll10_diff',
       'turnovers_roll10_diff', 'steals_roll10_diff', 'blocks_roll10_diff',
       'plusMinusPoints_roll10_diff', 'win_roll10_diff', 'rest_days_diff',
       'b2b_diff']

df_mrp = df_match_RP[ll_match_rp].dropna()
y_mrp  = df_mrp['win']
r_dic = {}

#Loop that iterates over each column in the above list, fits, and calculates the accuracy
#Only models/variables that yield results better than chance are reported
for col in ll_match_rp:
    if col == 'win':continue
    kf       = KFold(n_splits=5)
    stat_ary = np.zeros((3, 5))
    x_tr, x_te, y_tr, y_te = train_test_split(df_mrp[col], y_mrp, random_state=17, test_size=0.2)
    
    for i, (train_ix, test_ix) in enumerate(kf.split(x_tr)):
       xr = x_tr.iloc[train_ix].values.reshape(-1,1)
       yr = y_tr.iloc[train_ix]
       xh = x_tr.iloc[test_ix].values.reshape(-1,1)
       yh = y_tr.iloc[test_ix]
       nb = GaussianNB()
       nb.fit(xr, yr)

       y_pred = nb.predict(xh)
       acc    = 1.0*sum(y_pred==yh) / len(y_pred)
       prob   = nb.predict_proba(xh)
       roc    = roc_auc_score(yh, prob[:,1])
       prec   = precision_score(yh, y_pred)

       stat_ary[0][i] = acc
       stat_ary[1][i] = roc
       stat_ary[2][i] = prec

    if (stat_ary[0].mean() > 0.5 and stat_ary[1].mean() > 0.5 and stat_ary[2].mean() > 0.5):
       rstr = '%s Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = %.3f(%.3f),%.3f(%.3f), %.3f(%.3f)'%(
          col, stat_ary[0].mean(),stat_ary[0].std(), stat_ary[1].mean(),stat_ary[1].std(),stat_ary[2].mean(),stat_ary[2].std())
       acc_m = stat_ary[0].mean()
       r_dic[rstr] = acc_m

#Sorts the results by descending mean accuracty and prints the results
r_sorted = {k : v for k, v in sorted(r_dic.items(), key = lambda item: item[1], reverse=True)}

print('Match Regular + Playoffs Results')
for key, value in r_sorted.items():
   print(key)


Match Regular + Playoffs Results
plusMinusPoints_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.632(0.010),0.671(0.006), 0.650(0.010)
win_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.627(0.011),0.658(0.009), 0.645(0.012)
home_plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.614(0.007),0.629(0.007), 0.624(0.007)
home_win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.609(0.008),0.616(0.005), 0.622(0.007)
fieldGoalsPercentage_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.599(0.008),0.606(0.013), 0.609(0.007)
away_plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.595(0.006),0.610(0.009), 0.610(0.007)
teamScore_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.592(0.008),0.599(0.011), 0.603(0.008)
away_win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.591(0.008),0.604(0.007), 0.610(0.009)
away_fieldGoalsPercentage_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.58

In [13]:
#Naive Bayes using match variables that we would have access to before a prediction 
#Reg data set
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import roc_auc_score, precision_score

ll_match_rg = ['home_rest_days', 'home_b2b', 'win', 'home_teamScore_roll10',
       'home_fieldGoalsPercentage_roll10',
       'home_threePointersPercentage_roll10',
       'home_freeThrowsPercentage_roll10', 'home_reboundsOffensive_roll10',
       'home_reboundsDefensive_roll10', 'home_assists_roll10',
       'home_turnovers_roll10', 'home_steals_roll10', 'home_blocks_roll10',
       'home_plusMinusPoints_roll10', 'home_win_roll10', 'away_rest_days', 
       'away_b2b', 'away_teamScore_roll10', 'away_fieldGoalsPercentage_roll10',
       'away_threePointersPercentage_roll10',
       'away_freeThrowsPercentage_roll10', 'away_reboundsOffensive_roll10',
       'away_reboundsDefensive_roll10', 'away_assists_roll10',
       'away_turnovers_roll10', 'away_steals_roll10', 'away_blocks_roll10',
       'away_plusMinusPoints_roll10', 'away_win_roll10',
       'teamScore_roll10_diff', 'fieldGoalsPercentage_roll10_diff',
       'threePointersPercentage_roll10_diff',
       'freeThrowsPercentage_roll10_diff', 'reboundsOffensive_roll10_diff',
       'reboundsDefensive_roll10_diff', 'assists_roll10_diff',
       'turnovers_roll10_diff', 'steals_roll10_diff', 'blocks_roll10_diff',
       'plusMinusPoints_roll10_diff', 'win_roll10_diff', 'rest_days_diff',
       'b2b_diff']

df_mrg = df_match_RP[ll_match_rg].dropna()
y_mrg  = df_mrg['win']
r_dic = {}

#Loop that iterates over each column in the above list, fits, and calculates the accuracy
#Only models/variables that yield results better than chance are reported
for col in ll_match_rg:
    if col == 'win':continue
    kf       = KFold(n_splits=5)
    stat_ary = np.zeros((3, 5))
    x_tr, x_te, y_tr, y_te = train_test_split(df_mrg[col], y_mrg, random_state=17, test_size=0.2)
    
    for i, (train_ix, test_ix) in enumerate(kf.split(x_tr)):
       xr = x_tr.iloc[train_ix].values.reshape(-1,1)
       yr = y_tr.iloc[train_ix]
       xh = x_tr.iloc[test_ix].values.reshape(-1,1)
       yh = y_tr.iloc[test_ix]
       nb = GaussianNB()
       nb.fit(xr, yr)

       y_pred = nb.predict(xh)
       acc    = 1.0*sum(y_pred==yh) / len(y_pred)
       prob   = nb.predict_proba(xh)
       roc    = roc_auc_score(yh, prob[:,1])
       prec   = precision_score(yh, y_pred)

       stat_ary[0][i] = acc
       stat_ary[1][i] = roc
       stat_ary[2][i] = prec

    if (stat_ary[0].mean() > 0.5 and stat_ary[1].mean() > 0.5 and stat_ary[2].mean() > 0.5):
       rstr = '%s Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = %.3f(%.3f),%.3f(%.3f), %.3f(%.3f)'%(
          col, stat_ary[0].mean(),stat_ary[0].std(), stat_ary[1].mean(),stat_ary[1].std(),stat_ary[2].mean(),stat_ary[2].std())
       acc_m = stat_ary[0].mean()
       r_dic[rstr] = acc_m

#Sorts the results by descending mean accuracty and prints the results
r_sorted = {k : v for k, v in sorted(r_dic.items(), key = lambda item: item[1], reverse=True)}

print('Match Regular Results')
for key, value in r_sorted.items():
   print(key)


Match Regular Results
plusMinusPoints_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.632(0.010),0.671(0.006), 0.650(0.010)
win_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.627(0.011),0.658(0.009), 0.645(0.012)
home_plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.614(0.007),0.629(0.007), 0.624(0.007)
home_win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.609(0.008),0.616(0.005), 0.622(0.007)
fieldGoalsPercentage_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.599(0.008),0.606(0.013), 0.609(0.007)
away_plusMinusPoints_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.595(0.006),0.610(0.009), 0.610(0.007)
teamScore_roll10_diff Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.592(0.008),0.599(0.011), 0.603(0.008)
away_win_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.591(0.008),0.604(0.007), 0.610(0.009)
away_fieldGoalsPercentage_roll10 Mean Acc(STD), Mean ROC(STD), Mean Prec(STD) = 0.583(0.010),0.

Naive Bayes Base Model Conclusions

In general, there is not a significant differece between the regular season games data set and the regular season + playoff data set when taking into accout the means and standard deviations of the statistic tests.

A base model of just predicting if a team will win based upon the whether the game is a home game is 57.7 +- 0.8 %
A base model of just predicting if a team will win based upon the mean field goal percentage is      68.7 +- 0.4 %